
/**
 * TODO: Insert description here. (generated by lkary)
 */
public class CodePracticeMain {


  public static void main(String[] args) {


    String[] strings = { "abcdef", " 78032soa", "I hope this helps.", "78032soa3"};

    for (int i = 0; i < strings.length; i++) {
      System.out.println("String: " + strings[i] + " " + 
          StringProblems.hasAllUniqueCharacters2(strings[i]));
      System.out.println("String: " + strings[i] + " " + StringProblems.reverseString(strings[i]));
    }
    
    int[] bars = {2, 3, 4, 3, 2, 6, 4, 9, 1};
    
    System.out.print("Water: " + new FloodingBarGraph().solve(bars));
    
    System.out.println("\n\nString Permutations:");
    StringProblems.printPermutations("abcd");
    
    
    IntervalProblems intervalProblems = new IntervalProblems();
    
    Interval[] intervals = new Interval[5];
    intervals[0] = new Interval(0, 1);
    intervals[1] = new Interval(3, 7);
    intervals[2] = new Interval(6, 19);
    intervals[3] = new Interval(27, 28);
    intervals[4] = new Interval(56, 57);
    
    intervalProblems.findUnion(intervals);

  }

}
