import java.util.HashMap;


/**
 * TODO: Insert description here. (generated by lkary)
 */
public class StringProblems {

  /**
   * Problem:
   * Implement an algorithm to determine if a string has all unique characters.
   * @param string the input string.
   */
  public static boolean hasAllUniqueCharacters(String string) {
    HashMap<Character, Integer> map = new HashMap<Character, Integer>();
    char character;
    for (int i = 0; i < string.length(); i++) {
      character = string.charAt(i);
      if (map.containsKey(character)) {
        return false;
      } else {
        map.put(string.charAt(i), 0);
      }
    }
    return true;
  }

}
